a = input('Digite algo: ')
print('O que você digitou é {}.'.format(type(a)))
print(a.isnumeric())
print(a.isalnum())
print(a.isalpha())
print(a.isdecimal())
print(a.isspace())
print(a.isupper())
